apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
spec:
  selector:
    matchLabels:
      app: mynginx
  replicas: 2
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
      - name: mynginxcon
        image: nginx:tagVersion
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mynginx-svc
spec:
  selector:
    app: mynginx
  ports:
  - port: 8001
    targetPort: 80
  type: NodePort
